import type { Metadata } from "next";
import "./globals.css";
import { Kanit } from "next/font/google";
// import localFont from "next/font/local";

const kanit = Kanit({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-kanit",
});

// const stolenFont = localFont({
//   src: "../public/ducker-stolen-font.ttf",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={kanit.className}>{children}</body>
    </html>
  );
}
